- name: Copy over base sshd_config
  copy:
    src: files/sshd_config
    dest: /etc/ssh/sshd_config

- name: Add public key (maybe) for Ansible access
  debug:
    msg: "hello"

- name: Restart SSH Service
  service:
    name: sshd
    state: restarted
