[linux_vms]
oracle
ubuntu
mgmt

[server_intro]
10.0.0.103 ansible_user=ansible ansible_port=22 ansible_ssh_private_key_file=~/.ssh/id_ed25519_ansible


[proxmox_nodes]
proxmox1
proxmox2
proxmox3

[dc]
dc1.haydenlab.local

[dc:vars]
ansible_connection=winrm
ansible_port=5985
ansible_winrm_scheme=http
ansible_winrm_transport=ntlm
ansible_user=HAYDENLAB\hcraig
ansible_password=IbaneAeolus000!
ansible_winrm_server_cert_validation=ignore
